name: ScoreTrading
main: io.github.Alligrater.ScoreTrading
version: 1.0
commands:
  scoreshop: 
    description: Buy items from the score shop.
    usage: /scoreshop
  sshop: 
    description: Buy items from the score shop.
    usage: /sshop
  scoretrading: 
    description: manage values.
    usage: /scoretrading [reload/set/add] [..value] [..player]
  strade: 
    description: manage values.
    usage: /strade [reload/set/add] [..value] [..player]
  myscore: 
    description: what is my score
    usage: /myscore
  score: 
    description: what is my score
    usage: /score
  shoptool: 
    description: add to shop
    usage: /shoptool